[Version]
Class=IEXPRESS
SEDVersion=3
[Options]
PackagePurpose=InstallApp
ShowInstallProgramWindow=0
HideExtractAnimation=1
UseLongFileName=1
InsideCompressed=0
CAB_FixedSize=0
CAB_ResvCodeSigning=0
RebootMode=N
InstallPrompt=Installer MemoPrise sur ce PC ?
DisplayLicense=
FinishMessage=
TargetName=D:\Creation\Deepseek_test\Calendar\distribution\Installer-MemoPrise.exe
FriendlyName=MemoPrise
AppLaunched=powershell.exe -NoProfile -ExecutionPolicy Bypass -File Install.ps1
PostInstallCmd=<None>
AdminQuietInstCmd=
UserQuietInstCmd=
SourceFiles=SourceFiles
[Strings]
FILE0=MemoPrise.exe
FILE1=Install.ps1
[SourceFiles]
SourceFiles0=D:\Creation\Deepseek_test\Calendar\distribution\MemoPrise\
SourceFiles1=D:\Creation\Deepseek_test\Calendar\distribution\
[SourceFiles0]
%FILE0%=
[SourceFiles1]
%FILE1%=
